(() => {
  const COACH = {
    ISSUE: { starters:["The legal issue is whether…","The issue before the court is whether…"], bridges:["under","when","because","where"], closes:["under the applicable legal standard…","and whether…"] },
    RULE: { starters:["The governing rule provides that…","Under the applicable legal standard,…"], bridges:["when","if","unless","because"], closes:["unless…","when…","as required by…"] },
    HOLDING: { starters:["The court held that…","The court concluded that…"], bridges:["because","to the extent that","but","while"], closes:["therefore…","but did not…","leaving…"] },
    REASONING: { starters:["The court reasoned that…","The court explained that…"], bridges:["because","however","although","since"], closes:["therefore…","thus…","as a result…"] },
    REMEDY: { starters:["As a result, the court…","The court therefore ordered…"], bridges:["rather than","while","but","until"], closes:["while leaving…","pending…","and retained…"] },
    LIMITS: { starters:["The court did not decide…","The decision leaves unresolved…"], bridges:["but","while","instead","because"], closes:["leaving…","for later determination…","at this stage…"] },
    NEXT: { starters:["The next step is…","The court directed…"], bridges:["after","before","within","once"], closes:["which may…","before…","after which…"] }
  };

  function styles(){if(document.getElementById("statuteWritingCoachStyles"))return;const s=document.createElement("style");s.id="statuteWritingCoachStyles";s.textContent=`
  .writing-help{margin-top:8px;border-top:1px solid var(--border,#ddd);padding-top:8px;font:12px/1.45 system-ui,sans-serif}.writing-help-toggle{border:0;background:transparent;color:var(--muted,#666);font:600 11px system-ui;padding:4px 0;cursor:pointer;text-decoration:underline;text-underline-offset:3px}.thread-coach{margin-top:7px;padding:10px;border:1px solid var(--border,#ddd);border-radius:7px;background:rgba(120,120,120,.035)}.thread-coach[hidden]{display:none}.thread-title{font-weight:700;margin-bottom:2px}.thread-sub{font-size:11px;color:var(--muted,#666);margin-bottom:9px}.thread-stage{display:grid;grid-template-columns:62px 1fr;gap:8px;margin:7px 0;align-items:start}.thread-stage-label{font-size:9px;font-weight:700;letter-spacing:.07em;color:var(--muted,#777);padding-top:6px}.thread-options{display:flex;flex-wrap:wrap;gap:5px}.thread-chip{border:1px solid var(--border,#ccc);background:var(--panel,#fff);color:inherit;border-radius:5px;padding:5px 7px;font:500 11px system-ui;cursor:pointer}.thread-chip:hover,.thread-chip:focus-visible{border-color:currentColor;outline:none}.thread-tip{font-size:10px;color:var(--muted,#777);margin-top:8px}.thread-check{margin-top:8px;padding-top:7px;border-top:1px solid var(--border,#ddd);font-size:11px;color:var(--muted,#666)}@media(max-width:700px){.thread-stage{grid-template-columns:1fr;gap:3px}.thread-stage-label{padding-top:0}}
  `;document.head.appendChild(s)}

  function insert(textarea,text){const value=textarea.value;const start=textarea.selectionStart??value.length,end=textarea.selectionEnd??value.length;const before=value.slice(0,start),after=value.slice(end);const space=before && !/\s$/.test(before)?" ":"";textarea.value=before+space+text+after;const pos=(before+space+text).length;textarea.focus();textarea.setSelectionRange(pos,pos);textarea.dispatchEvent(new Event("input",{bubbles:true}))}

  function checkThread(text,label){const t=text.trim();if(!t)return "Write the thought roughly first. The sentence does not need to be polished.";const notes=[];if(/\b(they|things?|stuff)\b/i.test(t))notes.push("name the actor or legal action");if(t.split(/\s+/).length>38)notes.push("consider whether this is really two threads");if(label==="ISSUE"&&!/\bwhether\b/i.test(t))notes.push("test whether the issue can be framed with ‘whether’");if(label==="REASONING"&&!/\b(because|since|therefore|thus|although|however)\b/i.test(t))notes.push("show the connection between the reason and conclusion");return notes.length?`Before saving the thread: ${notes.join("; ")}.`:"Good thread shape. Now verify that every legal proposition is supported by the source."}

  function panel(config,textarea,label){const p=document.createElement("div");p.className="thread-coach";p.hidden=true;p.innerHTML=`<div class="thread-title">Build this thread</div><div class="thread-sub">Get the thought into one usable sentence. Statute gives you the path — you supply the legal substance.</div><div class="thread-stage" data-stage="start"><div class="thread-stage-label">START</div><div class="thread-options"></div></div><div class="thread-stage" data-stage="middle"><div class="thread-stage-label">DEVELOP</div><div class="thread-options"></div></div><div class="thread-stage" data-stage="close"><div class="thread-stage-label">CLOSE</div><div class="thread-options"></div></div><div class="thread-tip">These are connectors, not answers. Skip any stage you do not need.</div><div class="thread-check"></div>`;
    [["start",config.starters],["middle",config.bridges],["close",config.closes]].forEach(([stage,items])=>{const box=p.querySelector(`[data-stage="${stage}"] .thread-options`);items.forEach(x=>{const b=document.createElement("button");b.type="button";b.className="thread-chip";b.textContent=x;b.addEventListener("click",()=>insert(textarea,x));box.appendChild(b)})});
    const refresh=()=>p.querySelector(".thread-check").textContent=checkThread(textarea.value,label);textarea.addEventListener("input",refresh);refresh();return p}

  function enhance(){const guide=document.getElementById("guidePane");if(!guide)return;guide.querySelectorAll(".analysis-step").forEach(step=>{if(step.dataset.threadCoach)return;const label=step.querySelector("summary small")?.textContent.trim().toUpperCase(),textarea=step.querySelector("textarea"),config=COACH[label];if(!textarea||!config)return;step.dataset.threadCoach="true";const wrap=document.createElement("div");wrap.className="writing-help";const toggle=document.createElement("button");toggle.type="button";toggle.className="writing-help-toggle";toggle.textContent="Writing help · Build this thread";const p=panel(config,textarea,label);toggle.addEventListener("click",()=>{p.hidden=!p.hidden;if(!p.hidden)textarea.focus()});wrap.append(toggle,p);textarea.insertAdjacentElement("afterend",wrap)})}

  function wire(){styles();const a=document.getElementById("modeAnalyze");if(a&&!a.dataset.writingCoachWired){a.dataset.writingCoachWired="true";a.addEventListener("click",()=>setTimeout(enhance,30))}document.getElementById("tabGuide")?.addEventListener("click",()=>setTimeout(enhance,0))}
  document.addEventListener("DOMContentLoaded",wire)
})();